// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzZkCLvTeol5f-feA6y4Bc1dRo9R1KU8E',
    appId: '1:977737337403:web:16baad44dfeeff78ce2a1e',
    messagingSenderId: '977737337403',
    projectId: 'augmenti-965a7',
    authDomain: 'augmenti-965a7.firebaseapp.com',
    storageBucket: 'augmenti-965a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmSR8UMewRqAX7cCfC9HWI1xFHaf-0axo',
    appId: '1:977737337403:android:a70a7748a79a0ffdce2a1e',
    messagingSenderId: '977737337403',
    projectId: 'augmenti-965a7',
    storageBucket: 'augmenti-965a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCelSIK9o3siFri0foG2FxHUsErkWcaH6s',
    appId: '1:977737337403:ios:8e1ab36e16e7578ace2a1e',
    messagingSenderId: '977737337403',
    projectId: 'augmenti-965a7',
    storageBucket: 'augmenti-965a7.appspot.com',
    iosBundleId: 'com.example.augmenti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCelSIK9o3siFri0foG2FxHUsErkWcaH6s',
    appId: '1:977737337403:ios:8e1ab36e16e7578ace2a1e',
    messagingSenderId: '977737337403',
    projectId: 'augmenti-965a7',
    storageBucket: 'augmenti-965a7.appspot.com',
    iosBundleId: 'com.example.augmenti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzZkCLvTeol5f-feA6y4Bc1dRo9R1KU8E',
    appId: '1:977737337403:web:641f2bfb47bd1294ce2a1e',
    messagingSenderId: '977737337403',
    projectId: 'augmenti-965a7',
    authDomain: 'augmenti-965a7.firebaseapp.com',
    storageBucket: 'augmenti-965a7.appspot.com',
  );
}
